### ISSUE TITLE
Plugin Load Error - v1.16.5 Minecraft

### ISSUE THREAD

**Issue by togosh** [trevorzucker/NameHide#8]
Hey Trevor, I love the plugin!, having trouble loading it on Minecraft v1.16.5

```
[00:50:23 INFO]: [NameHide] Enabling NameHide v1.4
[00:50:23 ERROR]: Error occurred while enabling NameHide v1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/Entity
        at codes.zucker.NameHide.Main.onEnable(Main.java:14) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-504]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-504]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-504]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-504]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-504]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.5.jar:git-Paper-504]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-504]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.5.jar:git-Paper-504]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-504]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_15_R1.Entity
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:116) ~[patched_1.16.5.jar:git-Paper-504]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-504]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        ... 11 more
```

**Comment by trevorzucker** [comment]
Plugin has been updated. See [this](https://github.com/trevorzucker/NameHide/releases/tag/1.5)
